image: gitlab.iqm.fi:5005/iqm/qe/kqcircuits:kqc-test-02

cache:
  key: "$CI_PROJECT_ID-$CI_COMMIT_REF_SLUG"
  paths:
    - .pip-cache

before_script:
  - ci/init_kqc.sh

test:
  stage: test
  parallel:
    matrix:
      - KLAYOUT_VERSION: [0.26.11, 0.26.12, 0.27.0, 0.27.1]
  script:
    - pip install -Iv klayout==$KLAYOUT_VERSION
    - tox
  artifacts:
    reports:
      junit: test_report.xml
  only:
    - master
    - merge_requests
    - tags
  tags:
    - docker

verify_documentation:
  stage: test
  script:
    - Xvfb :99 -screen 0 640x480x24 -nolisten tcp &
    - cd docs
    - make html SPHINXOPTS="-W --keep-going"
  only:
    - merge_requests
  tags:
    - docker

check_confidential_strings:
  stage: test
  script:
    - bash check_files_for_strings.sh "$KQC_CONFIDENTIAL_STRINGS"
  only:
    refs:
      - merge_requests
    variables:
      - $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"
  tags:
    - docker


pages:
  stage: deploy
  script:
    - Xvfb :99 -screen 0 640x480x24 -nolisten tcp &
    - cd docs
    - make html SPHINXOPTS="-W --keep-going"
    - find _build/html -name "*.html" -exec sed -i 's#github.com/iqm-finland/KQCircuits#$KQC_REPOSITORY_STRING#g' {} +
    - mv _build/html ../public
  artifacts:
    paths:
    - public
  only:
    - master
  tags:
    - docker
