name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    container: ghcr.io/iqm-finland/kqcircuits
    strategy:
      fail-fast: false
      matrix:
        klayout_version: [0.26.11, 0.26.12, 0.27.0, 0.27.1]
    steps:
      - uses: actions/checkout@v2
      - name: Init KQCircuits
        run: ci/init_kqc.sh
      - name: Select KLayout version
        run: pip install -Iv klayout==${{ matrix.klayout_version }}
      - name: Run tests
        run: tox
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: Test results (KLayout=${{ matrix.klayout_version }})
          path: test_report.xml

  test_non_linux:
    name: Tests (non-🐧)
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest]
        klayout_version: [0.26.11, 0.26.12, 0.27.0, 0.27.1]
    steps:
      - uses: actions/checkout@v2
      - name: macOS setup
        run: |
          brew install python
          ln -s -f /usr/local/bin/python3.7 /usr/local/bin/python
        if: ${{ matrix.os == 'macos-latest' }}
      - name: Init KQCircuits
        run: pip3 install -e "python[docs,tests]"
        continue-on-error: true
      - name: Select KLayout version
        run: pip3 install -Iv klayout==${{ matrix.klayout_version }}
      - name: Run tests
        run: tox
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: Test results (${{ matrix.os }} KLayout=${{ matrix.klayout_version }})
          path: test_report.xml

  publish_test_results:
    name: Publish test results
    needs: [ test, test_non_linux ]
    runs-on: ubuntu-latest
    if: success() || failure()
    steps:
      - name: Download test results
        uses: actions/download-artifact@v2
        with:
          path: artifacts
      - name: Publish test results
        uses: EnricoMi/publish-unit-test-result-action@v1
        with:
          files: artifacts/**/*.xml
          check_name: Test results

  verify_documentation:
    name: Verify documentation
    runs-on: ubuntu-latest
    container: ghcr.io/iqm-finland/kqcircuits
    steps:
      - uses: actions/checkout@v2
      - name: Init KQCircuits
        run: ci/init_kqc.sh
      - name: Make docs
        run: |
          Xvfb :99 -screen 0 640x480x24 -nolisten tcp &
          cd docs
          make html SPHINXOPTS="-W --keep-going"
      - name: Docs to artifact
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: docs
          path: docs/_build/html/

  pages:
    name: Deploy documentation
    needs: [ test, test_non_linux, verify_documentation ]
    runs-on: ubuntu-latest
    container: ghcr.io/iqm-finland/kqcircuits
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v2
      - name: Download docs artifact
        uses: actions/download-artifact@v2
        with:
          name: docs
          path: public
      - name: Install rsync  # https://github.com/JamesIves/github-pages-deploy-action#using-a-container-
        run: apt-get update && apt-get install -y rsync
      - name: Upload pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: public